CREATE TABLE `t_user_201910` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `city_id` INT(12) DEFAULT NULL COMMENT '城市',
  `sex` TINYINT(2) DEFAULT NULL COMMENT '性别',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT '电话',
  `email` VARCHAR(32) DEFAULT NULL COMMENT '邮箱',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `password` VARCHAR(32) DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `t_user_201911` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(64) DEFAULT NULL COMMENT '名称',
  `city_id` INT(12) DEFAULT NULL COMMENT '城市',
  `sex` TINYINT(2) DEFAULT NULL COMMENT '性别',
  `phone` VARCHAR(32) DEFAULT NULL COMMENT '电话',
  `email` VARCHAR(32) DEFAULT NULL COMMENT '邮箱',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `password` VARCHAR(32) DEFAULT NULL COMMENT '密码',
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;